apiVersion: v1
kind: Service
metadata:
  name: order-service-1
  labels:
    app: order-service-1
spec:
  type: ClusterIP
  selector:
    app: order-service-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9002